# until we have a unique application_name make a hash out of the input params values
# so you will not be able to have 2 ServiceInstances with the same settings in a project
params_string: "{{ namespace }}::{{ _apb_plan_id }}::{{ aws_access_key }}::{{ aws_secret_key }}::{{ aws_cloudformation_role_arn }}::{{ region }}::{{ DBInstanceClass }}::{{ AllocatedStorageAndIops }}::{{ EngineVersion }}::{{ MysqlServerTimezone }}::{{ VpcId }}::{{ PubliclyAccessible }}::{{ AccessCidr }}"
params_hash: "{{ params_string | checksum }}"

# params
MultiAZ: false
NumberOfAvailabilityZones: "2"
AvailabilityZones: "auto"
CidrSize: "28"
CidrBlocks: "auto"
application_name_alnum: "{{ application_name | regex_replace('[^a-zA-Z0-9]') }}"
DBName: "{{ application_name_alnum[0:63] }}"
PortNumber: 13306
StorageEncrypted: true
StorageType: io1
CopyTagsToSnapshot: false
BackupRetentionPeriod: 0
MonitoringInterval: "60"
AllowMajorVersionUpgrade: false
AutoMinorVersionUpgrade: true
MasterUsername: "master"
MasterUserPassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=41') }}"
PreferredBackupWindow: "04:00-06:00"
PreferredMaintenanceWindowDay: Sat
PreferredMaintenanceWindowStartTime: 06:00
PreferredMaintenanceWindowEndTime: 07:00