apiVersion: v1
kind: Template
metadata:
  name: hello-world
parameters:
  - name: namespace
  - name: service_class_name
objects:
  - apiVersion: servicecatalog.k8s.io/v1alpha1
    kind: Instance
    metadata:
      name: hello-world
      namespace: ${namespace}
    spec:
      serviceClassName: ${service_class_name}
      planName: default
      parameters: {}
