- name: Launch RDS MySQL cluster
  cloudformation:
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   stack_name: "apb-RDS-{{ stack_identifier }}"
   state: "present"
   region: "{{ region }}"
   disable_rollback: false
   template: "{{ role_path }}/files/rds-mysql.template"
   template_parameters:
     ApplicationName: "{{ ApplicationName }}"
     VpcId: "{{ VpcId }}"
     NumberOfAvailabilityZones: "{{ NumberOfAvailabilityZones | string }}"
     PreferredBackupWindow: "{{ PreferredBackupWindow }}"
     PreferredMaintenanceWindowDay: "{{ PreferredMaintenanceWindowDay }}"
     PreferredMaintenanceWindowStartTime: "{{ PreferredMaintenanceWindowStartTime }}"
     PreferredMaintenanceWindowEndTime: "{{ PreferredMaintenanceWindowEndTime }}"
     MonitoringInterval: "{{ MonitoringInterval | string }}"
     AvailabilityZones: "{{ AvailabilityZones }}"
     CidrBlocks: "{{ CidrBlocks }}"
     AccessCidr: "{{ AccessCidr }}"
     AllocatedStorageAndIops: "{{ AllocatedStorageAndIops }}"
     MasterUsername: "{{ MasterUsername }}"
     MasterUserPassword: "{{ MasterUserPassword }}"
     AllowMajorVersionUpgrade: "{{ AllowMajorVersionUpgrade | string }}"
     StorageType: "{{ StorageType }}"
     MultiAZ: "{{ MultiAZ | string }}"
     AutoMinorVersionUpgrade: "{{ AutoMinorVersionUpgrade | string }}"
     StorageEncrypted: "{{ StorageEncrypted | string }}"
     BackupRetentionPeriod: "{{ BackupRetentionPeriod | string }}"
     PortNumber: "{{ PortNumber | string }}"
     CopyTagsToSnapshot: "{{ CopyTagsToSnapshot | string }}"
     PubliclyAccessible: "{{ PubliclyAccessible | string }}"
     DBInstanceClass: "{{ DBInstanceClass }}"
     DBName: "{{ DBName }}"
     EngineVersion: "{{ EngineVersion }}"
     MysqlServerTimezone: "{{ MysqlServerTimezone }}"
   tags:
     Stack: "ansible-cloudformation"
     Application: "ansible-rds-mysql"
     Description: "{{ ansible_user_id }} RDS {{ ApplicationName }}"
  register: rds

- name: Check for RDS CloudFormation error logs
  debug:
    var: rds.log

- name: Encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: "mysql"
      DB_PASSWORD: "{{ MasterUserPassword }}"
      DB_NAME: "{{ DBName }}"
      DB_HOST: "{{ rds.stack_outputs.EndpointAddress }}"
      DB_PORT: "{{ PortNumber | string }}"
      DB_USER: "{{ MasterUsername }}"
  when: rds.log | length < 1
