- name: include plan vars
  include_vars:
    file: "{{ _apb_plan_id }}.yml"
- name: generate b62 hash
  shell: "16to62 {{ params_hash }}"
  register: command_output
- name: set fact
  set_fact:
    stack_suffix: "{{ command_output.stdout }}"
- name: Log stack suffix
  debug:
    msg: "stack_suffix: {{ stack_suffix }}"
- name: generate cidrs
  block:
  - name: generate cidrs
    shell: "getcidrs {{ CidrSize }} {{ NumberOfAvailabilityZones }} {{ VpcId }} {{ region }}"
    register: command_output
  - name: set fact
    set_fact:
      CidrBlocks: "{{ command_output.stdout }}"
  when: CidrBlocks == "auto"
- name: generate azs
  block:
  - name: generate azs
    shell: "getazs {{ NumberOfAvailabilityZones }} {{ region }}"
    register: command_output
  - name: set fact
    set_fact:
      AvailabilityZones: "{{ command_output.stdout }}"
  when: AvailabilityZones == "auto"
- name: Launch RDS MySQL cluster
  cloudformation:
    stack_name: "apb-RDS-{{ stack_suffix }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: false
    template: "{{ role_path }}/files/rds-mysql.template"
    role_arn: "{{ aws_cloudformation_role_arn }}"
    template_parameters:
      ApplicationName: "{{ application_name }}"
      VpcId: "{{ VpcId }}"
      NumberOfAvailabilityZones: "{{ NumberOfAvailabilityZones | string }}"
      PreferredBackupWindow: "{{ PreferredBackupWindow }}"
      PreferredMaintenanceWindowDay: "{{ PreferredMaintenanceWindowDay }}"
      PreferredMaintenanceWindowStartTime: "{{ PreferredMaintenanceWindowStartTime }}"
      PreferredMaintenanceWindowEndTime: "{{ PreferredMaintenanceWindowEndTime }}"
      MonitoringInterval: "{{ MonitoringInterval | string }}"
      AvailabilityZones: "{{ AvailabilityZones }}"
      CidrBlocks: "{{ CidrBlocks }}"
      AccessCidr: "{{ AccessCidr }}"
      AllocatedStorageAndIops: "{{ AllocatedStorageAndIops }}"
      MasterUsername: "{{ MasterUsername }}"
      MasterUserPassword: "{{ MasterUserPassword }}"
      AllowMajorVersionUpgrade: "{{ AllowMajorVersionUpgrade | string }}"
      StorageType: "{{ StorageType }}"
      MultiAZ: "{{ MultiAZ | string }}"
      AutoMinorVersionUpgrade: "{{ AutoMinorVersionUpgrade | string }}"
      StorageEncrypted: "{{ StorageEncrypted | string }}"
      BackupRetentionPeriod: "{{ BackupRetentionPeriod | string }}"
      PortNumber: "{{ PortNumber | string }}"
      CopyTagsToSnapshot: "{{ CopyTagsToSnapshot | string }}"
      PubliclyAccessible: "{{ PubliclyAccessible | string }}"
      DBInstanceClass: "{{ DBInstanceClass }}"
      DBName: "{{ DBName }}"
      EngineVersion: "{{ EngineVersion }}"
      MysqlServerTimezone: "{{ MysqlServerTimezone }}"
    tags:
      ServiceBrokerId: "{{ application_name }}"
  register: rds

- name: Check for RDS CloudFormation error logs
  debug:
    var: rds.log
- name: Encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: "mysql"
      DB_PASSWORD: "{{ MasterUserPassword }}"
      DB_NAME: "{{ DBName }}"
      DB_HOST: "{{ rds.stack_outputs.EndpointAddress }}"
      DB_PORT: "{{ PortNumber | string }}"
      DB_USER: "{{ MasterUsername }}"
  when: rds.log | length < 1
