- name: Deploy rds to openshift
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no

  - role: provision-rds-apb-openshift
